name: Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Generate coverage report
      run: |
        pip install -e .
        pip install pytest pytest-cov
        pytest --cov --junitxml=junit.xml -o junit_family=legacy
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}