name: Multi-os tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Hatch
      uses: pypa/hatch@install        

    - name: Run tests
      run: hatch test --all
